ignoredBuiltDependencies:
  - bigint-buffer
  - blake-hash
  - bufferutil
  - es5-ext
  - keccak
  - protobufjs
  - react-native-inappbrowser-reborn
  - secp256k1
  - sharp
  - tiny-secp256k1
  - unrs-resolver
  - usb
  - utf-8-validate
